preprocess:
  input: SourceData/train.csv
  output: SourceData/processed
  models: models/

experimentation:
  experiment_name: podcast_listentime
  data: SourceData/processed/transformed.csv
  models: models/
  exp_models:
    sgd_regressor:
      loss: 'squared_error'
      penalty: 'elasticnet'
      iterations: 600 
    svm:
      iterations: 600
    adaboost:
      n_estimators: 1000


test:
  data: SourceData/test.csv